//
// Created by Francesca Sani on 11/07/23.
//

#ifndef LAB_DI_PROGRAMMAZIONE_FRANCESCA_SANI_LISTA_H
#define LAB_DI_PROGRAMMAZIONE_FRANCESCA_SANI_LISTA_H


class Lista {

};


#endif //LAB_DI_PROGRAMMAZIONE_FRANCESCA_SANI_LISTA_H
